version: '2.1'
services: 
        
        tools:
                build: ./telegram
                privileged: true
                restart: always
                ports: 
                        - 3000
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                        io.balena.features.balena-api: 1
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
        
        ei-processing:
                build: ./ei-processing
                privileged: true
                restart: always
                network_mode: host
                container_name: ei-processing
                ports: 
                        - 8080
                depends_on:
                        - tools
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                environment:
                        - UDEV=1
                devices:
                        - '/dev:/dev'
        web:
                build: ./web
                container_name: web
                privileged: true
                restart: always
                network_mode: host
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                ports: 
                        - 80
                depends_on:
                        - ei-processing
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                links:
                        - ei-processing

        hostname:
                image: balenablocks/hostname
                restart: no                                     # Required to avoid container restarting indefinitely
                labels:
                        io.balena.features.supervisor-api: 1    # Required to interact with the supervisor
                environment:
                        SET_HOSTNAME: birdwatcher
        wifi-connect:
                build: ./wifi-connect
                restart: unless-stopped
                network_mode: host
                privileged: true
                ports: 
                        - 8100
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.firmware: '1'
                cap_add:
                        - NET_ADMIN
                environment:
                        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
                        PORTAL_SSID: "BIRD-WIFI-AP"
                        PORTAL_LISTENING_PORT: "8100"

volumes:
        shared-data:
        shared-media:
        
